apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy-store-deployment
  labels:
    app: comfy-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comfy-store
  template:
    metadata:
      labels:
        app: comfy-store
    spec:
      containers:
        - name: comfy-shoppe
          image: ankitnimbolkar/comfy-shoppe:0.0.2.RELEASE
          ports:
            - containerPort: 5501
