apiVersion: v1
kind: Service
metadata:
  name: comfy-store-service
spec:
  type: NodePort
  selector:
    app: comfy-store
  ports:
    - protocol: TCP
      port: 5501
      targetPort: 5501
      nodePort: 30088
